export enum MechanismType {
    PHYSICAL = "PHYSICAL",
    CHEMICAL = "CHEMICAL",
    BIOLOGICAL = "BIOLOGICAL",
    MECHANICAL = "MECHANICAL",
    ELECTRICAL = "ELECTRICAL",
    COMPUTATIONAL = "COMPUTATIONAL",
    ECONOMIC = "ECONOMIC",
    SOCIAL = "SOCIAL",
    PSYCHOLOGICAL = "PSYCHOLOGICAL",
    ORGANIZATIONAL = "ORGANIZATIONAL",
    ENVIRONMENTAL = "ENVIRONMENTAL",
    LOGICAL = "LOGICAL",
    MATHEMATICAL = "MATHEMATICAL",
    AI_REASONING = "AI_REASONING",
    GENERAL = "GENERAL",
    UNKNOWN = "UNKNOWN"
}

export enum MechanismLinkType {
    ACTIVATES = "ACTIVATES",
    INHIBITS = "INHIBITS",
    AMPLIFIES = "AMPLIFIES",
    SUPPRESSES = "SUPPRESSES",
    FEEDBACK = "FEEDBACK",
    DEPENDS_ON = "DEPENDS_ON",
    COMPETES_WITH = "COMPETES_WITH",
    COOPERATES_WITH = "COOPERATES_WITH",
    ENABLES = "ENABLES"
}

export enum MechanismStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    HYPOTHETICAL = "HYPOTHETICAL",
    VALIDATED = "VALIDATED",
    REJECTED = "REJECTED"
}

export enum MechanismTriggerType {
    EVENT = "EVENT",
    CONDITION = "CONDITION",
    THRESHOLD = "THRESHOLD",
    EXTERNAL_INPUT = "EXTERNAL_INPUT",
    MISSION_ACTION = "MISSION_ACTION",
    TIME = "TIME",
    RESOURCE_AVAILABILITY = "RESOURCE_AVAILABILITY",
    USER_ACTION = "USER_ACTION"
}
