export enum SessionStatus {
    CREATED = "CREATED",
    ANALYZING = "ANALYZING",
    RUNNING = "RUNNING",
    PAUSED = "PAUSED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    ERROR = "ERROR"
}

export enum ThoughtStatus {
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    PAUSED = "PAUSED",
    COMPLETED = "COMPLETED",
    REJECTED = "REJECTED",
    MERGED = "MERGED"
}

export enum ModuleType {
    MEMORY = "MEMORY",
    EXPERIENCE = "EXPERIENCE",
    KNOWLEDGE = "KNOWLEDGE",
    WORLD_MODEL = "WORLD_MODEL",
    PROCESS = "PROCESS",
    MECHANISM = "MECHANISM",
    PRINCIPLE = "PRINCIPLE",
    HYPOTHESIS = "HYPOTHESIS",
    RESEARCH = "RESEARCH",
    SIMULATION = "SIMULATION",
    DISCOVERY = "DISCOVERY",
    PLANNER = "PLANNER",
    CRITIC = "CRITIC",
    REFLECTION = "REFLECTION",
    META_COGNITION = "META_COGNITION"
}

export enum AttentionFocus {
    MISSION = "MISSION",
    KNOWLEDGE_GAP = "KNOWLEDGE_GAP",
    RISK = "RISK",
    FAILURE = "FAILURE",
    SIMULATION = "SIMULATION",
    RESEARCH = "RESEARCH",
    HYPOTHESIS = "HYPOTHESIS",
    DISCOVERY = "DISCOVERY",
    USER_CONSTRAINTS = "USER_CONSTRAINTS"
}
